/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.6-dev at Thu Jun  2 17:28:40 2022. */

#include "md.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t md_start_transfert_cmd_fields[2] = {
    PB_FIELD(  1, UENUM   , OPTIONAL, STATIC  , FIRST, md_start_transfert_cmd_t, cmd_id, cmd_id, 0),
    PB_LAST_FIELD
};

const pb_field_t md_transfert_complete_cmd_fields[2] = {
    PB_FIELD(  1, UENUM   , OPTIONAL, STATIC  , FIRST, md_transfert_complete_cmd_t, cmd_id, cmd_id, 0),
    PB_LAST_FIELD
};

const pb_field_t md_stop_transfert_cmd_fields[2] = {
    PB_FIELD(  1, UENUM   , OPTIONAL, STATIC  , FIRST, md_stop_transfert_cmd_t, cmd_id, cmd_id, 0),
    PB_LAST_FIELD
};

const pb_field_t md_transfert_error_cmd_fields[5] = {
    PB_FIELD(  1, UENUM   , OPTIONAL, STATIC  , FIRST, md_transfert_error_cmd_t, cmd_id, cmd_id, 0),
    PB_FIELD(  2, UENUM   , OPTIONAL, STATIC  , OTHER, md_transfert_error_cmd_t, err_type, cmd_id, 0),
    PB_FIELD(  3, UINT32  , OPTIONAL, STATIC  , OTHER, md_transfert_error_cmd_t, block_addr, err_type, 0),
    PB_FIELD(  4, UINT32  , OPTIONAL, STATIC  , OTHER, md_transfert_error_cmd_t, seq_number, block_addr, 0),
    PB_LAST_FIELD
};

const pb_field_t md_mem_percent_cmd_fields[3] = {
    PB_FIELD(  1, UENUM   , OPTIONAL, STATIC  , FIRST, md_mem_percent_cmd_t, cmd_id, cmd_id, 0),
    PB_FIELD(  2, UINT32  , OPTIONAL, STATIC  , OTHER, md_mem_percent_cmd_t, mem_percent, cmd_id, 0),
    PB_LAST_FIELD
};

const pb_field_t md_info_req_cmd_fields[2] = {
    PB_FIELD(  1, UENUM   , OPTIONAL, STATIC  , FIRST, md_info_req_cmd_t, cmd_id, cmd_id, 0),
    PB_LAST_FIELD
};

const pb_field_t md_info_resp_cmd_fields[7] = {
    PB_FIELD(  1, UENUM   , OPTIONAL, STATIC  , FIRST, md_info_resp_cmd_t, cmd_id, cmd_id, 0),
    PB_FIELD(  2, UINT32  , OPTIONAL, STATIC  , OTHER, md_info_resp_cmd_t, start_block_addr, cmd_id, 0),
    PB_FIELD(  3, UINT32  , OPTIONAL, STATIC  , OTHER, md_info_resp_cmd_t, end_block_addr, start_block_addr, 0),
    PB_FIELD(  4, UINT32  , OPTIONAL, STATIC  , OTHER, md_info_resp_cmd_t, total_block_nbr, end_block_addr, 0),
    PB_FIELD(  5, UINT32  , OPTIONAL, STATIC  , OTHER, md_info_resp_cmd_t, mem_min_block_addr, total_block_nbr, 0),
    PB_FIELD(  6, UINT32  , OPTIONAL, STATIC  , OTHER, md_info_resp_cmd_t, mem_max_block_addr, mem_min_block_addr, 0),
    PB_LAST_FIELD
};

const pb_field_t md_ctrlpt_cmd_fields[8] = {
    PB_ONEOF_FIELD(cmd,   1, MESSAGE , ONEOF, STATIC  , FIRST, md_ctrlpt_cmd_t, start_transfert, start_transfert, &md_start_transfert_cmd_fields),
    PB_ONEOF_FIELD(cmd,   2, MESSAGE , ONEOF, STATIC  , FIRST, md_ctrlpt_cmd_t, transfert_complete, transfert_complete, &md_transfert_complete_cmd_fields),
    PB_ONEOF_FIELD(cmd,   3, MESSAGE , ONEOF, STATIC  , FIRST, md_ctrlpt_cmd_t, stop_transfert, stop_transfert, &md_stop_transfert_cmd_fields),
    PB_ONEOF_FIELD(cmd,   4, MESSAGE , ONEOF, STATIC  , FIRST, md_ctrlpt_cmd_t, transfert_error, transfert_error, &md_transfert_error_cmd_fields),
    PB_ONEOF_FIELD(cmd,   5, MESSAGE , ONEOF, STATIC  , FIRST, md_ctrlpt_cmd_t, mem_percent, mem_percent, &md_mem_percent_cmd_fields),
    PB_ONEOF_FIELD(cmd,   6, MESSAGE , ONEOF, STATIC  , FIRST, md_ctrlpt_cmd_t, info_req, info_req, &md_info_req_cmd_fields),
    PB_ONEOF_FIELD(cmd,   7, MESSAGE , ONEOF, STATIC  , FIRST, md_ctrlpt_cmd_t, info_resp, info_resp, &md_info_resp_cmd_fields),
    PB_LAST_FIELD
};

const pb_field_t md_raw_data_item_fields[4] = {
    PB_FIELD(  1, UENUM   , OPTIONAL, STATIC  , FIRST, md_raw_data_item_t, type, type, 0),
    PB_FIELD(  2, UINT64  , OPTIONAL, STATIC  , OTHER, md_raw_data_item_t, timestamp, type, 0),
    PB_FIELD(  3, BYTES   , OPTIONAL, STATIC  , OTHER, md_raw_data_item_t, payload, timestamp, 0),
    PB_LAST_FIELD
};

const pb_field_t md_data_chunk_fields[5] = {
    PB_FIELD(  1, UENUM   , OPTIONAL, STATIC  , FIRST, md_data_chunk_t, cmd_id, cmd_id, 0),
    PB_FIELD(  2, UINT32  , OPTIONAL, STATIC  , OTHER, md_data_chunk_t, block_addr, cmd_id, 0),
    PB_FIELD(  3, UINT32  , OPTIONAL, STATIC  , OTHER, md_data_chunk_t, seq_number, block_addr, 0),
    PB_FIELD(  4, MESSAGE , REPEATED, STATIC  , OTHER, md_data_chunk_t, data, seq_number, &md_raw_data_item_fields),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(md_ctrlpt_cmd_t, cmd.start_transfert) < 65536 && pb_membersize(md_ctrlpt_cmd_t, cmd.transfert_complete) < 65536 && pb_membersize(md_ctrlpt_cmd_t, cmd.stop_transfert) < 65536 && pb_membersize(md_ctrlpt_cmd_t, cmd.transfert_error) < 65536 && pb_membersize(md_ctrlpt_cmd_t, cmd.mem_percent) < 65536 && pb_membersize(md_ctrlpt_cmd_t, cmd.info_req) < 65536 && pb_membersize(md_ctrlpt_cmd_t, cmd.info_resp) < 65536 && pb_membersize(md_ctrlpt_cmd_t, cmd.start_transfert) < 65536 && pb_membersize(md_ctrlpt_cmd_t, cmd.transfert_complete) < 65536 && pb_membersize(md_ctrlpt_cmd_t, cmd.stop_transfert) < 65536 && pb_membersize(md_ctrlpt_cmd_t, cmd.transfert_error) < 65536 && pb_membersize(md_ctrlpt_cmd_t, cmd.mem_percent) < 65536 && pb_membersize(md_ctrlpt_cmd_t, cmd.info_req) < 65536 && pb_membersize(md_ctrlpt_cmd_t, cmd.info_resp) < 65536 && pb_membersize(md_data_chunk_t, data[0]) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_md_start_transfert_cmd_md_transfert_complete_cmd_md_stop_transfert_cmd_md_transfert_error_cmd_md_mem_percent_cmd_md_info_req_cmd_md_info_resp_cmd_md_ctrlpt_cmd_md_raw_data_item_md_data_chunk)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(md_ctrlpt_cmd_t, cmd.start_transfert) < 256 && pb_membersize(md_ctrlpt_cmd_t, cmd.transfert_complete) < 256 && pb_membersize(md_ctrlpt_cmd_t, cmd.stop_transfert) < 256 && pb_membersize(md_ctrlpt_cmd_t, cmd.transfert_error) < 256 && pb_membersize(md_ctrlpt_cmd_t, cmd.mem_percent) < 256 && pb_membersize(md_ctrlpt_cmd_t, cmd.info_req) < 256 && pb_membersize(md_ctrlpt_cmd_t, cmd.info_resp) < 256 && pb_membersize(md_ctrlpt_cmd_t, cmd.start_transfert) < 256 && pb_membersize(md_ctrlpt_cmd_t, cmd.transfert_complete) < 256 && pb_membersize(md_ctrlpt_cmd_t, cmd.stop_transfert) < 256 && pb_membersize(md_ctrlpt_cmd_t, cmd.transfert_error) < 256 && pb_membersize(md_ctrlpt_cmd_t, cmd.mem_percent) < 256 && pb_membersize(md_ctrlpt_cmd_t, cmd.info_req) < 256 && pb_membersize(md_ctrlpt_cmd_t, cmd.info_resp) < 256 && pb_membersize(md_data_chunk_t, data[0]) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_md_start_transfert_cmd_md_transfert_complete_cmd_md_stop_transfert_cmd_md_transfert_error_cmd_md_mem_percent_cmd_md_info_req_cmd_md_info_resp_cmd_md_ctrlpt_cmd_md_raw_data_item_md_data_chunk)
#endif


/* @@protoc_insertion_point(eof) */
